@startuml
class GameManager {
    -gameMode
    -players
    -acceptPlayers
    -nbPlayers
}

class Player {
    -pseudo
    -score
}

class GameMode {
    -name
    -startingScore
    -endingScore
    -gameObjects
    -minTimeToSpawn
    -maxTimeToSpawn
}

class GameModeManager {
    -gameModes
}

class GameObject {
    -type
    -enabled
    -points
    -timeout
}

class GameObjectRandomizer {
    -availableGameObjects
    -generatedGameObjects
}

class RandomGameObject {
    -id
    -gameObject
    -point
}

class PlayerScore {
    -player
    -mode
    -score
    -date
}

GameModeManager "1" -- "*" GameMode
GameObjectRandomizer - RandomGameObject
GameObject"*" - "1" GameMode
GameManager "1" - "*" Player
GameMode "1" - "1" GameObjectRandomizer

@enduml
