@startuml
class GameManager {
    [[GameManager.html]]
    -gameMode
    -players
    -acceptPlayers
    -nbPlayers
}

class PlayerScore {
    -player
    -mode
    -score
    -date
}

class Player {
    [[Player.html]]
    -pseudo
    -score
}

class GameMode {
    [[GameMode.html]]
    -name
    -startingScore
    -endingScore
    -gameObjects
    -minTimeToSpawn
    -maxTimeToSpawn
}

class GameModeManager {
    [[GameModeManager.html]]
    -gameModes
}

class GameObject {
    [[GameObject.html]]
    -type
    -enabled
    -points
    -timeout
}

class RandomGameObject {
    [[GameObjectRandomizer.html]]
    -id
    -gameObject
    -point
}

GameModeManager "1" -- "*" GameMode
GameMode "1" - "*" GameObject
GameManager "1" - "*" Player
GameMode "1" - "1" RandomGameObject
Player "1" -- "*" PlayerScore
@enduml
