@startuml
class GameManager {
    [[GameManager.html]]
    -gameMode
    -players
    -acceptPlayers
    -nbPlayers
}

class PlayerScore {
    -player
    -mode
    -score
    -date
}

class Player {
    -pseudo
    -score
}

class GameMode {
    -name
    -startingScore
    -endingScore
    -gameObjects
    -minTimeToSpawn
    -maxTimeToSpawn
}

class GameModeManager {
    -gameModes
}

class GameObject {
    -type
    -enabled
    -points
    -timeout
}

class RandomGameObject {
    -id
    -gameObject
    -point
}

GameMode "1" - "1" RandomGameObject
GameMode "1" - "*" GameObject
GameModeManager "1" -- "*" GameMode
Player "1" - "*" PlayerScore
GameManager "1" - "*" Player
@enduml
