@startuml

Client -> Serveur : JOIN <i>{username}</i>

Serveur -> Serveur : Le pseudo est-il déjà utilisé ?

Client <-x Serveur : USERNAME_USED

Serveur -> Serveur : Est-ce que le lobby est ouvert ?

Client <-x Serveur : GAME_FULL

Serveur -> Serveur : Ajout du joueur

Serveur -> Client : JOINED <i>{GameMode}</i>

Client -> Client : Chargement de la configuration

Serveur --> Client : BEGIN_GAME

Serveur -> Serveur : Temps aléatoire

Serveur --> Client : SHOW_OBJECT <i>{Random Game Object}</i>

Client --> Serveur : OBJECT_TOUCHED <i>{Object ID}</i>

Serveur -> Serveur : Vérifie les scores et définit si la partie est terminée

Serveur --> Client : SCORES_UPDATE <i>{player's score}</i>

Client --> Serveur

Serveur --> Client

Client --> Serveur

Serveur -> Serveur : Vérifie les scores et définit si la partie est terminée

Serveur --> Client : WINNER <i>{winner's pseudo, players}</i>

Serveur --> Client : END_OF_GAME

@enduml
